### ISSUE TITLE
Derive Ord, Generics for PrivateKey/PublicKey

### ISSUE THREAD

**Issue by ndmitchell** [vincenthz/hs-crypto-pubkey-types#13]
Additionally Hashable would be handy, but I guess you won't want to due to the extra dependency.

**Comment by TomMD** [comment]
Having ordering, or even equality (which is there), of secrets can encourage dangerous uses.  I'd rather have orphaned instances perhaps in a different module with big warnings or some scary module naming.

**Comment by ndmitchell** [comment]
That's a good reason for making them private. But if they aren't private, you might as well provide easy helpers without orphans.
